### ISSUE TITLE
Windows Support

### ISSUE THREAD

**Issue by dhirschfeld** [conda-forge/nano-feedstock#3]
It would be great if there were Windows builds available! 

I'm using nano on headless Windows servers and containers but it would be significantly easier for me if it were conda installable. 

***xref:*** https://github.com/ContinuumIO/anaconda-issues/issues/1485

**Comment by scopatz** [comment]
Great idea! Pull requests welcome!

**Comment by dhirschfeld** [comment]
Ha! :stuck_out_tongue_winking_eye:

The build looks fairly complicated so I'm unlikely to get to it any time soon :/

**Comment by scopatz** [comment]
Alright, anyone is welcome to submit a PR though!

**Comment by dhirschfeld** [comment]
In case it's of use to any other Windows users I created a package which can be installed with:
```
conda install -c dhirschfeld nano
```
I cheated though and just used the binaries from https://github.com/lhmouse/nano-win

<details>
<summary><b><tt>meta.yaml</tt></b></summary>

```
package:
  name: nano
  version: "3.0.0.post004+gdf170f15"

source:
  url: https://files.lhmouse.com/nano-win/nano-win_7375_v3.0-4-gdf170f15.7z

requirements:
  build:
    - m2-p7zip

test:
  commands:
    - nano -h

about:
  home: https://github.com/lhmouse/nano-win
  summary: "GNU nano text editor for Windows"
```
</details>
<br>
<details>
<summary><b><tt>bld.bat</tt></b></summary>

```
setlocal enableextensions enabledelayedexpansion

start /wait %PREFIX%\Library\usr\lib\p7zip\7za.exe x nano-win_7375_v3.0-4-gdf170f15.7z -y -r -o%SRC_DIR%

xcopy %SRC_DIR%\x86_64-w64-mingw32\bin\nano.exe %PREFIX%\Library\bin /F /Y
if %ERRORLEVEL% NEQ 0 goto FAIL

xcopy %SRC_DIR%\x86_64-w64-mingw32\share\nano %PREFIX%\Library\share\nano /F /I /E /Y
if %ERRORLEVEL% NEQ 0 goto FAIL

xcopy %SRC_DIR%\x86_64-w64-mingw32\share\doc\nano %PREFIX%\Library\share\doc\nano /F /I /E /Y
if %ERRORLEVEL% NEQ 0 goto FAIL

exit /B 0

:FAIL
echo Command failed with ERRORLEVEL %ERRORLEVEL%
exit /B 1
```
</details>
